import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import styled from "styled-components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Arjit Johar | Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/** animated background */}

      {/** navigation bar with sections called about me, demos, interests, resume, contact me */}

      {/** animated text showing name in the center of the screen */}

      {/** footer with contact information bottom right */}

      {/** picture of myself should animate in from thin air - looks baller as fuck */}

      {/** color pallete to follow: https://coolors.co/dcdcdd-c5c3c6-46494c-4c5c68-1985a1 */}

      <h1> Demos</h1>
    </div>
  );
}
